name: Build Kernel

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get update
        sudo apt-get install lzma gettext libmpc-dev u-boot-tools libncurses5-dev:amd64 
        sudo apt-get autoremove --purge
        sudo apt-get clean
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV

    - name: Build
      run: sudo bash build_kernel.sh

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ github.workspace }}/artifact/
